{% set name = "pydantic-core" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_core-{{ version }}.tar.gz
  sha256: 480d49cc0e33ebf3d084f81d7bb5b4d8c16f1d126244a5b7dae9ecc4ae5b766a

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.14,<0.15                   # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
  host:
    - pip
    - python
    - maturin >=0.14,<0.15
    - typing_extensions
  run:
    - python
    - typing_extensions  # [py<311]

test:
  imports:
    - pydantic_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydantic/pydantic-core
  dev_url: https://github.com/pydantic/pydantic-core
  summary: Core validation logic for pydantic written in rust
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - samuelcolvin
    - adriangb
    - dmontagu
